### ISSUE TITLE
incorrect values of kc_l8 and kc_l8t

### ISSUE THREAD

**Issue by khouakhi** [cesarofs/agriwater#1]
I think the script doesn't read the correct lines of the radiance Min and Max from the L8 metadata file (below is the metadata structure as found within the L8 downloaded images) 

doy = 09
a = 1.8
b = 0.1
RG = 17
Ta = 27.9
ET0 = 3.8

kc_l8(doy , RG  , Ta,a ,b)

OGR data source with driver: ESRI Shapefile 
Source: "C:\Users\Cri\OneDrive..\LC08_L1TP_009053_20200109_20200114_01_T1_2020-01-09\mask.shp", layer: "mask"
with 1 features
It has 11 fields
Integer64 fields read as strings:  tessellate extrude visibility drawOrder 
Warning messages:
1: In readOGR("mask.shp") : Z-dimension discarded
2: In kc_l8(doy, RG, Ta, a, b) : NAs introduced by coercion

--
GROUP = L1_METADATA_FILE
  GROUP = METADATA_FILE_INFO
    ORIGIN = "Image courtesy of the U.S. Geological Survey"
    REQUEST_ID = "0702001132136_00011"
    LANDSAT_SCENE_ID = "LC80090532020009LGN00"
    LANDSAT_PRODUCT_ID = "LC08_L1TP_009053_20200109_20200114_01_T1"
    COLLECTION_NUMBER = 01
    FILE_DATE = 2020-01-14T06:25:22Z
    STATION_ID = "LGN"
    PROCESSING_SOFTWARE_VERSION = "LPGS_13.1.0"
  END_GROUP = METADATA_FILE_INFO
  GROUP = PRODUCT_METADATA
    DATA_TYPE = "L1TP"
    COLLECTION_CATEGORY = "T1"
    ELEVATION_SOURCE = "GLS2000"
    OUTPUT_FORMAT = "GEOTIFF"
    SPACECRAFT_ID = "LANDSAT_8"
    SENSOR_ID = "OLI_TIRS"
    WRS_PATH = 9
    WRS_ROW = 53
    NADIR_OFFNADIR = "NADIR"
    TARGET_WRS_PATH = 9
    TARGET_WRS_ROW = 53
    DATE_ACQUIRED = 2020-01-09
    SCENE_CENTER_TIME = "15:17:31.7036040Z"
    CORNER_UL_LAT_PRODUCT = 11.16916
    CORNER_UL_LON_PRODUCT = -75.79315
    CORNER_UR_LAT_PRODUCT = 11.16744
    CORNER_UR_LON_PRODUCT = -73.71051
    CORNER_LL_LAT_PRODUCT = 9.06923
    CORNER_LL_LON_PRODUCT = -75.78802
    CORNER_LR_LAT_PRODUCT = 9.06784
    CORNER_LR_LON_PRODUCT = -73.71886
    CORNER_UL_PROJECTION_X_PRODUCT = 413400.000
    CORNER_UL_PROJECTION_Y_PRODUCT = 1234800.000
    CORNER_UR_PROJECTION_X_PRODUCT = 640800.000
    CORNER_UR_PROJECTION_Y_PRODUCT = 1234800.000
    CORNER_LL_PROJECTION_X_PRODUCT = 413400.000
    CORNER_LL_PROJECTION_Y_PRODUCT = 1002600.000
    CORNER_LR_PROJECTION_X_PRODUCT = 640800.000
    CORNER_LR_PROJECTION_Y_PRODUCT = 1002600.000
    PANCHROMATIC_LINES = 15481
    PANCHROMATIC_SAMPLES = 15161
    REFLECTIVE_LINES = 7741
    REFLECTIVE_SAMPLES = 7581
    THERMAL_LINES = 7741
    THERMAL_SAMPLES = 7581
    FILE_NAME_BAND_1 = "LC08_L1TP_009053_20200109_20200114_01_T1_B1.TIF"
    FILE_NAME_BAND_2 = "LC08_L1TP_009053_20200109_20200114_01_T1_B2.TIF"
    FILE_NAME_BAND_3 = "LC08_L1TP_009053_20200109_20200114_01_T1_B3.TIF"
    FILE_NAME_BAND_4 = "LC08_L1TP_009053_20200109_20200114_01_T1_B4.TIF"
    FILE_NAME_BAND_5 = "LC08_L1TP_009053_20200109_20200114_01_T1_B5.TIF"
    FILE_NAME_BAND_6 = "LC08_L1TP_009053_20200109_20200114_01_T1_B6.TIF"
    FILE_NAME_BAND_7 = "LC08_L1TP_009053_20200109_20200114_01_T1_B7.TIF"
    FILE_NAME_BAND_8 = "LC08_L1TP_009053_20200109_20200114_01_T1_B8.TIF"
    FILE_NAME_BAND_9 = "LC08_L1TP_009053_20200109_20200114_01_T1_B9.TIF"
    FILE_NAME_BAND_10 = "LC08_L1TP_009053_20200109_20200114_01_T1_B10.TIF"
    FILE_NAME_BAND_11 = "LC08_L1TP_009053_20200109_20200114_01_T1_B11.TIF"
    FILE_NAME_BAND_QUALITY = "LC08_L1TP_009053_20200109_20200114_01_T1_BQA.TIF"
    ANGLE_COEFFICIENT_FILE_NAME = "LC08_L1TP_009053_20200109_20200114_01_T1_ANG.txt"
    METADATA_FILE_NAME = "LC08_L1TP_009053_20200109_20200114_01_T1_MTL.txt"
    CPF_NAME = "LC08CPF_20200101_20200331_01.03"
    BPF_NAME_OLI = "LO8BPF20200109150321_20200109154600.01"
    BPF_NAME_TIRS = "LT8BPF20200101033839_20200111055053.01"
    RLUT_FILE_NAME = "LC08RLUT_20150303_20431231_01_12.h5"
  END_GROUP = PRODUCT_METADATA
  GROUP = IMAGE_ATTRIBUTES
    CLOUD_COVER = 0.01
    CLOUD_COVER_LAND = 0.01
    IMAGE_QUALITY_OLI = 9
    IMAGE_QUALITY_TIRS = 9
    TIRS_SSM_MODEL = "FINAL"
    TIRS_SSM_POSITION_STATUS = "ESTIMATED"
    TIRS_STRAY_LIGHT_CORRECTION_SOURCE = "TIRS"
    ROLL_ANGLE = -0.001
    SUN_AZIMUTH = 140.68864682
    SUN_ELEVATION = 48.21285663
    EARTH_SUN_DISTANCE = 0.9832990
    SATURATION_BAND_1 = "N"
    SATURATION_BAND_2 = "N"
    SATURATION_BAND_3 = "N"
    SATURATION_BAND_4 = "N"
    SATURATION_BAND_5 = "N"
    SATURATION_BAND_6 = "Y"
    SATURATION_BAND_7 = "Y"
    SATURATION_BAND_8 = "N"
    SATURATION_BAND_9 = "N"
    GROUND_CONTROL_POINTS_VERSION = 4
    GROUND_CONTROL_POINTS_MODEL = 377
    GEOMETRIC_RMSE_MODEL = 6.641
    GEOMETRIC_RMSE_MODEL_Y = 4.951
    GEOMETRIC_RMSE_MODEL_X = 4.426
    GROUND_CONTROL_POINTS_VERIFY = 98
    GEOMETRIC_RMSE_VERIFY = 4.911
    TRUNCATION_OLI = "UPPER"
  END_GROUP = IMAGE_ATTRIBUTES
  GROUP = MIN_MAX_RADIANCE
    RADIANCE_MAXIMUM_BAND_1 = 786.10071
    RADIANCE_MINIMUM_BAND_1 = -64.91645
    RADIANCE_MAXIMUM_BAND_2 = 804.97675
    RADIANCE_MINIMUM_BAND_2 = -66.47524
    RADIANCE_MAXIMUM_BAND_3 = 741.77917
    RADIANCE_MINIMUM_BAND_3 = -61.25637
    RADIANCE_MAXIMUM_BAND_4 = 625.51001
    RADIANCE_MINIMUM_BAND_4 = -51.65482
    RADIANCE_MAXIMUM_BAND_5 = 382.78091
    RADIANCE_MINIMUM_BAND_5 = -31.61017
    RADIANCE_MAXIMUM_BAND_6 = 95.19413
    RADIANCE_MINIMUM_BAND_6 = -7.86116
    RADIANCE_MAXIMUM_BAND_7 = 32.08552
    RADIANCE_MINIMUM_BAND_7 = -2.64963
    RADIANCE_MAXIMUM_BAND_8 = 707.90515
    RADIANCE_MINIMUM_BAND_8 = -58.45904
    RADIANCE_MAXIMUM_BAND_9 = 149.59946
    RADIANCE_MINIMUM_BAND_9 = -12.35397
    RADIANCE_MAXIMUM_BAND_10 = 22.00180
    RADIANCE_MINIMUM_BAND_10 = 0.10033
    RADIANCE_MAXIMUM_BAND_11 = 22.00180
    RADIANCE_MINIMUM_BAND_11 = 0.10033
  END_GROUP = MIN_MAX_RADIANCE
  GROUP = MIN_MAX_REFLECTANCE
    REFLECTANCE_MAXIMUM_BAND_1 = 1.210700
    REFLECTANCE_MINIMUM_BAND_1 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_2 = 1.210700
    REFLECTANCE_MINIMUM_BAND_2 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_3 = 1.210700
    REFLECTANCE_MINIMUM_BAND_3 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_4 = 1.210700
    REFLECTANCE_MINIMUM_BAND_4 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_5 = 1.210700
    REFLECTANCE_MINIMUM_BAND_5 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_6 = 1.210700
    REFLECTANCE_MINIMUM_BAND_6 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_7 = 1.210700
    REFLECTANCE_MINIMUM_BAND_7 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_8 = 1.210700
    REFLECTANCE_MINIMUM_BAND_8 = -0.099980
    REFLECTANCE_MAXIMUM_BAND_9 = 1.210700
    REFLECTANCE_MINIMUM_BAND_9 = -0.099980
  END_GROUP = MIN_MAX_REFLECTANCE
  GROUP = MIN_MAX_PIXEL_VALUE
    QUANTIZE_CAL_MAX_BAND_1 = 65535
    QUANTIZE_CAL_MIN_BAND_1 = 1
    QUANTIZE_CAL_MAX_BAND_2 = 65535
    QUANTIZE_CAL_MIN_BAND_2 = 1
    QUANTIZE_CAL_MAX_BAND_3 = 65535
    QUANTIZE_CAL_MIN_BAND_3 = 1
    QUANTIZE_CAL_MAX_BAND_4 = 65535
    QUANTIZE_CAL_MIN_BAND_4 = 1
    QUANTIZE_CAL_MAX_BAND_5 = 65535
    QUANTIZE_CAL_MIN_BAND_5 = 1
    QUANTIZE_CAL_MAX_BAND_6 = 65535
    QUANTIZE_CAL_MIN_BAND_6 = 1
    QUANTIZE_CAL_MAX_BAND_7 = 65535
    QUANTIZE_CAL_MIN_BAND_7 = 1
    QUANTIZE_CAL_MAX_BAND_8 = 65535
    QUANTIZE_CAL_MIN_BAND_8 = 1
    QUANTIZE_CAL_MAX_BAND_9 = 65535
    QUANTIZE_CAL_MIN_BAND_9 = 1
    QUANTIZE_CAL_MAX_BAND_10 = 65535
    QUANTIZE_CAL_MIN_BAND_10 = 1
    QUANTIZE_CAL_MAX_BAND_11 = 65535
    QUANTIZE_CAL_MIN_BAND_11 = 1
  END_GROUP = MIN_MAX_PIXEL_VALUE
  GROUP = RADIOMETRIC_RESCALING
    RADIANCE_MULT_BAND_1 = 1.2986E-02
    RADIANCE_MULT_BAND_2 = 1.3298E-02
    RADIANCE_MULT_BAND_3 = 1.2254E-02
    RADIANCE_MULT_BAND_4 = 1.0333E-02
    RADIANCE_MULT_BAND_5 = 6.3233E-03
    RADIANCE_MULT_BAND_6 = 1.5725E-03
    RADIANCE_MULT_BAND_7 = 5.3003E-04
    RADIANCE_MULT_BAND_8 = 1.1694E-02
    RADIANCE_MULT_BAND_9 = 2.4713E-03
    RADIANCE_MULT_BAND_10 = 3.3420E-04
    RADIANCE_MULT_BAND_11 = 3.3420E-04
    RADIANCE_ADD_BAND_1 = -64.92944
    RADIANCE_ADD_BAND_2 = -66.48854
    RADIANCE_ADD_BAND_3 = -61.26862
    RADIANCE_ADD_BAND_4 = -51.66515
    RADIANCE_ADD_BAND_5 = -31.61650
    RADIANCE_ADD_BAND_6 = -7.86274
    RADIANCE_ADD_BAND_7 = -2.65016
    RADIANCE_ADD_BAND_8 = -58.47073
    RADIANCE_ADD_BAND_9 = -12.35644
    RADIANCE_ADD_BAND_10 = 0.10000
    RADIANCE_ADD_BAND_11 = 0.10000
    REFLECTANCE_MULT_BAND_1 = 2.0000E-05
    REFLECTANCE_MULT_BAND_2 = 2.0000E-05
    REFLECTANCE_MULT_BAND_3 = 2.0000E-05
    REFLECTANCE_MULT_BAND_4 = 2.0000E-05
    REFLECTANCE_MULT_BAND_5 = 2.0000E-05
    REFLECTANCE_MULT_BAND_6 = 2.0000E-05
    REFLECTANCE_MULT_BAND_7 = 2.0000E-05
    REFLECTANCE_MULT_BAND_8 = 2.0000E-05
    REFLECTANCE_MULT_BAND_9 = 2.0000E-05
    REFLECTANCE_ADD_BAND_1 = -0.100000
    REFLECTANCE_ADD_BAND_2 = -0.100000
    REFLECTANCE_ADD_BAND_3 = -0.100000
    REFLECTANCE_ADD_BAND_4 = -0.100000
    REFLECTANCE_ADD_BAND_5 = -0.100000
    REFLECTANCE_ADD_BAND_6 = -0.100000
    REFLECTANCE_ADD_BAND_7 = -0.100000
    REFLECTANCE_ADD_BAND_8 = -0.100000
    REFLECTANCE_ADD_BAND_9 = -0.100000
  END_GROUP = RADIOMETRIC_RESCALING
  GROUP = TIRS_THERMAL_CONSTANTS
    K1_CONSTANT_BAND_10 = 774.8853
    K2_CONSTANT_BAND_10 = 1321.0789
    K1_CONSTANT_BAND_11 = 480.8883
    K2_CONSTANT_BAND_11 = 1201.1442
  END_GROUP = TIRS_THERMAL_CONSTANTS
  GROUP = PROJECTION_PARAMETERS
    MAP_PROJECTION = "UTM"
    DATUM = "WGS84"
    ELLIPSOID = "WGS84"
    UTM_ZONE = 18
    GRID_CELL_SIZE_PANCHROMATIC = 15.00
    GRID_CELL_SIZE_REFLECTIVE = 30.00
    GRID_CELL_SIZE_THERMAL = 30.00
    ORIENTATION = "NORTH_UP"
    RESAMPLING_OPTION = "CUBIC_CONVOLUTION"
  END_GROUP = PROJECTION_PARAMETERS
END_GROUP = L1_METADATA_FILE
END

**Comment by cesarofs** [comment]
Thanks for your comunication, Abdou Khouakhi,
I'm sorry by the late to answer you, hope your interest in using "agriwater" is still alive.

An improved version of the R package "agriwater" is now available on CRAN.
The conversion from raw Landsat-8 images into reflectances has been improved. I also updated the automatic acquisition of Landsat-8 metadata.

Please check the version 1.0.1 avaliable at CRAN 
https://cran.r-project.org/web/packages/agriwater/index.html
