### ISSUE TITLE
Problem in clipping

### ISSUE THREAD

**Issue by agronomofiorentini** [cesarofs/agriwater#2]
Dear creator,
Thanks to have develop this package, that i am trying to use it to estimate actual evapotraspiration from satellite image.

The satellite images that i am using have a spatial resolution of 3x3 m.

So the satellite images that i am trying to use is the following

<img width="957" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/193798706-10e15b83-b70e-4c4a-a7eb-25ac2d86c83c.png">

after use the evapo_s2 function i have the following actual evapotraspiration output.

<img width="563" alt="Screenshot_2" src="https://user-images.githubusercontent.com/66969646/193798978-4202e482-d16d-43c5-bdfa-0af48450538b.png">

I think the problem was related to the different crs between satellite images and shapefile, but their were the same.

Could you help me to solve this?

In order to improve the repex i have created and share it a google drive folder with all the data.

and the other parameters to run the code is the following

> a = 1.8
b = -0.008
RG = 17.6
Ta = 27.9
ET0 = 5.1
doy = 22

https://drive.google.com/drive/folders/1QE6HxuiSM5dJ2K2akt5MU9-Mx2E8xO9L?usp=sharing

**Comment by agronomofiorentini** [comment]
I have went line by line to identify where is the problem, and i have found that the problem is within the follow functions:

> Ws = acos(((-1) * tan(lati * pi/180)) * tan(Dec))
Emiss_atm = 0.9364 * (((-1) * log(Transm))^0.1135)

The first one is giving me back the follow error output
```
In acos(getValues(x)) : NaNs produced
```

The second function is giving me back the follow error output
```
In is.factor(values) : NaNs produced
```

**Comment by cesarofs** [comment]
Dear Marco Fiorentini,
Thanks a lot for using my R package and providing feedback to me.

Can you please try to change this to line

LAT <- (13+(4*long/60)+(Et/60))

To this one:

LAT <- (13-(4*long/60)+(Et/60))

This is the calculation of the local apparent time (LAT), I need to update the package to its version 1.1 to automatically change it according to the hemisphere and also improve the vignettes with the whole theory for it.

Please let me know if it works!

**Comment by agronomofiorentini** [comment]
Dear @cesarofs thanks for your feeback.

I have modified the lines that you suggested, but I didn't solve the problem.

This is the output of ET

<img width="716" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/194882653-1140c1d4-1e7a-4cd9-8897-ba3a26e8488a.png">

**Comment by agronomofiorentini** [comment]
any news about this issue?

**Comment by cesarofs** [comment]
Sorry by my late response. Are you still facing the same problem? I tried to run the `agriwater ` in this same area with an Sentinel-2 image sucessfully. So I need to investigate a little more on something in your original image.

**Comment by agronomofiorentini** [comment]
Thanks to reply. Actually i have the same problem as before. Could you please provide me the code that you have used?

I will share the original image that i am using wich is downloaded by google earth engine.

You can find the image here.

https://drive.google.com/drive/folders/1ysXVze1dfniIgvAl6dY3zTrjosBzJ9cX?usp=sharing

the layers are the follow 
```
b2 <- raster::raster(path, band=1)
b3 <- raster::raster(path, band=2)
b4 <- raster::raster(path, band=3)
b8 <- raster::raster(path, band=4)
```

**Comment by cesarofs** [comment]
@agronomofiorentini 
I refactored the `agriwater` package because the dependencies `rgdal` and `maptools` will be retired. In this manner, I noticed the new `terra` package has all the functions we need, so this is the only dependency of `agriwater` now. 

In our case, the main problem of the former `agriwater` code was:
- The raster file needs to be projected over a decimal degrees grid, not on UTM like the native Sentinel-2 imagery are
- The variable R was changed to match with the northern hemisphere solar behavior. It will be automatically found in the next version of `agriwater`.

Below is the screenshot and the new code. Please pay attention to some new useful functions from the new `terra` package.

![image](https://github.com/cesarofs/agriwater/assets/23387614/88097df9-5b45-4275-882f-3275a56f2aa7)

```
setwd('C:/issue_agriwater_marco')

library(terra)

b2 = rast('20230530T100031_20230530T100029_T33TUJ.tif',lyrs=1)
b2 = project(b2, "+proj=longlat +datum=WGS84")

b3 = rast('20230530T100031_20230530T100029_T33TUJ.tif',lyrs=2)
b3 = project(b3, "+proj=longlat +datum=WGS84")

b4 = rast('20230530T100031_20230530T100029_T33TUJ.tif',lyrs=3)
b4 = project(b4, "+proj=longlat +datum=WGS84")

b8 = rast('20230530T100031_20230530T100029_T33TUJ.tif',lyrs=4)
b8 = project(b8, "+proj=longlat +datum=WGS84")

b2 <- b2/10000
b3 <- b3/10000
b4 <- b4/10000
b8 <- b8/10000

Alb_Top = b2*0.32+b3*0.26+b4*0.25+b8*0.17
Alb_sur = 0.6054*Alb_Top + 0.0797
Alb_24 =  1.0223*Alb_sur + 0.0149
NDVI =(b8-b4)/(b8+b4)

lati <- long <- b2
xy <- crds(b2)
long[] <- xy[, 1]
lati[] <- xy[, 2]

#ficctional data
doy = 150
RG = 17.6
Ta = 27.9
a = 1.8
b = -0.008

map1 <- (long/long)*((2*pi)/365)*(doy-1)
Et <- (0.000075+0.001868*cos(map1)-0.032077*sin(map1)-0.014615*cos(2*map1)-0.04089*sin(2*map1))
LAT <- (13+(4*long/60)+(Et/60))
Dec <- 0.006918-0.399912*cos(map1)+0.070257*sin(map1)+0.006758*cos(2*map1)+0.000907*sin(2*map1)-0.002697*cos(3*map1)+0.00148*sin(3*map1)
W <- 15*(LAT-12)*(pi/180)
cos_zwn <- sin(lati*pi/180)*sin(Dec)+cos(lati*pi/180)*cos(Dec)*cos(W)
E0 <- (1.00011+0.034221*cos(map1)+0.00128*sin(map1)+0.000719*cos(2*map1)+0.000077*sin(2*map1))
Ws = acos(((-1)*tan(lati*pi/180))*tan(Dec))

# changed R equation
R =(Ws*sin(lati*pi/180)*sin(Dec))+(cos(lati*pi/180)*cos(Dec)*sin(Ws))

RsTOP_aux =(1367/pi)*E0*R
RsTOP = resample(RsTOP_aux, b2, method="bilinear")
Transm =(RG*11.6)/RsTOP
Rn_coeff =6.99*Ta-39.99
Rn =((1-Alb_24)*(RG*11.6))-(Rn_coeff*Transm)
Rn_MJ =Rn/11.6
slope =(4098*(0.6108*exp((17.27*(Ta))/((Ta)+237.3)))/((Ta)+237.3)^2)
LEeq = (slope*Rn)/(slope+0.066)
RR =Alb_24*RG
Emiss_atm = 0.9364*(((-1)*log(Transm))^0.1135)
Emiss_atm[Emiss_atm > 1] <- 1
RLdown_wm2 =(Emiss_atm*5.67*(10^(-8))*((Ta +273.15)^4))
RL_down =RLdown_wm2/11.6
RL_up =(RG-RR+RL_down-Rn_MJ)
Esurf_r1 <- NDVI
Esurf_r1[NDVI < 0] <- 1
Esurf_r1[NDVI >= 0] <- NA
Esurf_r2 <- 1.0035+0.0589*log(NDVI)
Esurf <- merge(Esurf_r1, Esurf_r2)
TS24 =((RL_up*11.6)/((Esurf*5.67)*(10^(-8))))^(0.25)
TS24[TS24 < 273.15] = NA
NDVI[NDVI <= 0] = NA
kc=exp((a)+(b*((TS24-273.15)/(Alb_24*NDVI))))

```

**Comment by agronomofiorentini** [comment]
Now it's working perfectly.

Thanks.
