### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [cesarofs/agriwater#3]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by rsbivand** [comment]
See also https://r-spatial.org/r/2023/04/10/evolution3.html. Fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
See also https://r-spatial.org/r/2023/05/15/evolution4.html, please update now! Neither `rgeos` nor `rgdal` are used at all, an unneeded `rgdal` option is used in some examples, but there the use suggests that you have been silencing essential warnings about your CRS handling.
This check log is when neither are in DESCRIPTION: 
[00check.log](https://github.com/cesarofs/agriwater/files/11677551/00check.log)
so some other use, simply use `terra` functionality. Six months have now elapsed since first warning, with no action your package will fail in October. If you want to keep it on CRAN, you must act NOW!

**Comment by cesarofs** [comment]
We the authors sincerely apologize for the delay. We were going to upload a 1.1 version soon, but I am uploading the version 1.0.1 immediately to fix the problems as requested and suggested here. Again, our sincere apologies.

**Comment by rsbivand** [comment]
The best apology is a successfully submitted fix!

**Comment by cesarofs** [comment]
The new fixed version (1.0.2) is on CRAN. Now the only depedency is `terra` package. CRAN results shows OK for 1.0.2, so the NOTE status from 1.0.1 is solved too.
