### ISSUE TITLE
Error in execution of "agriwater" package using Landsat 8 Data

### ISSUE THREAD

**Issue by adeel20112709** [cesarofs/agriwater#4]
Hello,
I am trying to use agriwater package to estimate actual ET using Landsat 8 data. I have arranged all the bands , shapefile and other surface variables in the same folder as mentioned in the article. When I run the package it shows error as described in the following picture. 
![微信截图_20230311162538](https://user-images.githubusercontent.com/74858735/224475084-08bf46c5-cc71-47cd-af5d-22ee487836b3.png)

The input data for package execution is gathered in the same folder as shown in picture bellow
 
![微信截图_20230311155451](https://user-images.githubusercontent.com/74858735/224475183-b0efa429-e6f9-4bf3-b533-4ea20e50eada.png)

I  have run the package on sentinel 2 data, it worked well but when I try for Landsat 8 data shows error. please guide me how can i fix this problem.
 
Regards,
ADEEL

**Comment by Luiz-Octavioo** [comment]
Hello adeel20112709, I'm facing the same issue when using Landsat 8 images. Did you manage to solve it? Any solutions?

**Comment by adeel20112709** [comment]
Hello Luiz, 
yeah I have solved this issue, you have to to use all the required bands and meta data file also , then this will work for Landsat imagery.

Good Luck, 
adeel

2023-08-12 04:04:08"Luiz Octavio" ***@***.***>wrote:

Hello adeel20112709, I'm facing the same issue when using Landsat 8 images. Did you manage to solve it? Any solutions?
